add_test( allocator.default /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=allocator.default]==])
set_tests_properties( allocator.default PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS allocator SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( allocator.default_temp /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=allocator.default_temp]==])
set_tests_properties( allocator.default_temp PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS allocator SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( allocator.arena /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=allocator.arena]==])
set_tests_properties( allocator.arena PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS allocator SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( allocator.linear_generic /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=allocator.linear_generic]==])
set_tests_properties( allocator.linear_generic PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS allocator SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( allocator.ring_generic /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=allocator.ring_generic]==])
set_tests_properties( allocator.ring_generic PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS allocator SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( allocator.arena_extended /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=allocator.arena_extended]==])
set_tests_properties( allocator.arena_extended PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS allocator SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( allocator.vm_arena /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=allocator.vm_arena]==])
set_tests_properties( allocator.vm_arena PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS allocator SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( allocator.vm_arena_generic /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=allocator.vm_arena_generic]==])
set_tests_properties( allocator.vm_arena_generic PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS allocator SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( allocator.vm /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=allocator.vm]==])
set_tests_properties( allocator.vm PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS allocator SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( allocator.linear /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=allocator.linear]==])
set_tests_properties( allocator.linear PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS allocator SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( allocator.ring /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=allocator.ring]==])
set_tests_properties( allocator.ring PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS allocator SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( allocator.temp /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=allocator.temp]==])
set_tests_properties( allocator.temp PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS allocator SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( array.test /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=array.test]==])
set_tests_properties( array.test PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS array SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( atomic.enum_constants /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=atomic.enum_constants]==])
set_tests_properties( atomic.enum_constants PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS atomic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( atomic.symbol_lookup /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=atomic.symbol_lookup]==])
set_tests_properties( atomic.symbol_lookup PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS atomic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( atomic.symbol_from_number /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=atomic.symbol_from_number]==])
set_tests_properties( atomic.symbol_from_number PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS atomic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( atomic.element_properties /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=atomic.element_properties]==])
set_tests_properties( atomic.element_properties PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS atomic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( atomic.inference_water /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=atomic.inference_water]==])
set_tests_properties( atomic.inference_water PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS atomic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( atomic.inference_amino_acid /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=atomic.inference_amino_acid]==])
set_tests_properties( atomic.inference_amino_acid PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS atomic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( atomic.inference_nucleic_acid /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=atomic.inference_nucleic_acid]==])
set_tests_properties( atomic.inference_nucleic_acid PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS atomic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( atomic.inference_ions /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=atomic.inference_ions]==])
set_tests_properties( atomic.inference_ions PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS atomic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( atomic.inference_fallbacks /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=atomic.inference_fallbacks]==])
set_tests_properties( atomic.inference_fallbacks PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS atomic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( atomic.backward_compatibility /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=atomic.backward_compatibility]==])
set_tests_properties( atomic.backward_compatibility PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS atomic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( bitop.test /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=bitop.test]==])
set_tests_properties( bitop.test PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS bitop SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( bitfield.bit_op /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=bitfield.bit_op]==])
set_tests_properties( bitfield.bit_op PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS bitfield SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( bitfield.realloc /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=bitfield.realloc]==])
set_tests_properties( bitfield.realloc PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS bitfield SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( bitfield.general /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=bitfield.general]==])
set_tests_properties( bitfield.general PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS bitfield SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( bitfield.serialization /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=bitfield.serialization]==])
set_tests_properties( bitfield.serialization PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS bitfield SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( bitfield.deserialize_base64 /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=bitfield.deserialize_base64]==])
set_tests_properties( bitfield.deserialize_base64 PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS bitfield SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( bitfield.iterator /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=bitfield.iterator]==])
set_tests_properties( bitfield.iterator PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS bitfield SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( element_guess_compat.all_pdb_validation /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=element_guess_compat.all_pdb_validation]==])
set_tests_properties( element_guess_compat.all_pdb_validation PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS element_guess_compat SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( str.parse_int /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=str.parse_int]==])
set_tests_properties( str.parse_int PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS str SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( str.perf_int /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=str.perf_int]==])
set_tests_properties( str.perf_int PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS str SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( str.parse_float /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=str.parse_float]==])
set_tests_properties( str.parse_float PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS str SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( str.perf_float /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=str.perf_float]==])
set_tests_properties( str.perf_float PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS str SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( str.extract_line /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=str.extract_line]==])
set_tests_properties( str.extract_line PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS str SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( str.edit_distance /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=str.edit_distance]==])
set_tests_properties( str.edit_distance PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS str SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( str.count_equal_chars /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=str.count_equal_chars]==])
set_tests_properties( str.count_equal_chars PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS str SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( hash.u32 /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=hash.u32]==])
set_tests_properties( hash.u32 PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS hash SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( hash.u64 /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=hash.u64]==])
set_tests_properties( hash.u64 PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS hash SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( hash.custom_type /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=hash.custom_type]==])
set_tests_properties( hash.custom_type PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS hash SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( edr.pullout /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=edr.pullout]==])
set_tests_properties( edr.pullout PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS edr SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( edr.orires /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=edr.orires]==])
set_tests_properties( edr.orires PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS edr SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( edr.ener /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=edr.ener]==])
set_tests_properties( edr.ener PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS edr SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( edr.dhdl /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=edr.dhdl]==])
set_tests_properties( edr.dhdl PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS edr SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( edr.comprehensive_validation /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=edr.comprehensive_validation]==])
set_tests_properties( edr.comprehensive_validation PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS edr SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( edr.nonexistent_file /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=edr.nonexistent_file]==])
set_tests_properties( edr.nonexistent_file PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS edr SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( cube.read_benzene /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=cube.read_benzene]==])
set_tests_properties( cube.read_benzene PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS cube SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( cube.read_A2B2 /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=cube.read_A2B2]==])
set_tests_properties( cube.read_A2B2 PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS cube SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( cube.serialize_deserialize /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=cube.serialize_deserialize]==])
set_tests_properties( cube.serialize_deserialize PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS cube SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( cube.nonexistent_file /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=cube.nonexistent_file]==])
set_tests_properties( cube.nonexistent_file PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS cube SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( cube.empty_path /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=cube.empty_path]==])
set_tests_properties( cube.empty_path PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS cube SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( intrinsics.memset /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=intrinsics.memset]==])
set_tests_properties( intrinsics.memset PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS intrinsics SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( intrinsics.memcpy /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=intrinsics.memcpy]==])
set_tests_properties( intrinsics.memcpy PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS intrinsics SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( intrinsics.test /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=intrinsics.test]==])
set_tests_properties( intrinsics.test PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS intrinsics SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( simd.sin_cos /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=simd.sin_cos]==])
set_tests_properties( simd.sin_cos PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS simd SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( simd.hsum /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=simd.hsum]==])
set_tests_properties( simd.hsum PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS simd SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( simd.hmax /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=simd.hmax]==])
set_tests_properties( simd.hmax PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS simd SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( simd.hmin /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=simd.hmin]==])
set_tests_properties( simd.hmin PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS simd SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( simd.exp /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=simd.exp]==])
set_tests_properties( simd.exp PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS simd SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( simd.fast_pow /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=simd.fast_pow]==])
set_tests_properties( simd.fast_pow PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS simd SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( vec_math.mat3 /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=vec_math.mat3]==])
set_tests_properties( vec_math.mat3 PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS vec_math SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( vec_math.mat4 /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=vec_math.mat4]==])
set_tests_properties( vec_math.mat4 PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS vec_math SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( os.path_canonical /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=os.path_canonical]==])
set_tests_properties( os.path_canonical PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS os SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( os.path_relative /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=os.path_relative]==])
set_tests_properties( os.path_relative PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS os SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( os.ram /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=os.ram]==])
set_tests_properties( os.ram PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS os SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( os.mem /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=os.mem]==])
set_tests_properties( os.mem PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS os SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( os.thread /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=os.thread]==])
set_tests_properties( os.thread PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS os SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( os.mutex /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=os.mutex]==])
set_tests_properties( os.mutex PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS os SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( os.semaphore /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=os.semaphore]==])
set_tests_properties( os.semaphore PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS os SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( os.file_read_lines /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=os.file_read_lines]==])
set_tests_properties( os.file_read_lines PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS os SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( pdb.parse_ordinary /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=pdb.parse_ordinary]==])
set_tests_properties( pdb.parse_ordinary PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS pdb SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( pdb.tryptophan /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=pdb.tryptophan]==])
set_tests_properties( pdb.tryptophan PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS pdb SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( pdb.unmatched_model_entry /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=pdb.unmatched_model_entry]==])
set_tests_properties( pdb.unmatched_model_entry PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS pdb SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( pdb.parse_trajectory /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=pdb.parse_trajectory]==])
set_tests_properties( pdb.parse_trajectory PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS pdb SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( pdb.trajectory_i /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=pdb.trajectory_i]==])
set_tests_properties( pdb.trajectory_i PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS pdb SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( pdb.create_system /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=pdb.create_system]==])
set_tests_properties( pdb.create_system PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS pdb SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( pdb.parse_nonexistent_file /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=pdb.parse_nonexistent_file]==])
set_tests_properties( pdb.parse_nonexistent_file PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS pdb SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( pdb.parse_empty_path /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=pdb.parse_empty_path]==])
set_tests_properties( pdb.parse_empty_path PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS pdb SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( gro.parse_small /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=gro.parse_small]==])
set_tests_properties( gro.parse_small PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS gro SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( gro.parse_big /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=gro.parse_big]==])
set_tests_properties( gro.parse_big PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS gro SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( gro.parse_small_water /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=gro.parse_small_water]==])
set_tests_properties( gro.parse_small_water PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS gro SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( gro.nonexistent_file /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=gro.nonexistent_file]==])
set_tests_properties( gro.nonexistent_file PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS gro SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( trr.trajectory_i /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=trr.trajectory_i]==])
set_tests_properties( trr.trajectory_i PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS trr SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( trr.nonexistent_file /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=trr.nonexistent_file]==])
set_tests_properties( trr.nonexistent_file PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS trr SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( trr.frame_boundary_conditions /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=trr.frame_boundary_conditions]==])
set_tests_properties( trr.frame_boundary_conditions PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS trr SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( mmcif.1fez /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=mmcif.1fez]==])
set_tests_properties( mmcif.1fez PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS mmcif SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( mmcif.2or2 /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=mmcif.2or2]==])
set_tests_properties( mmcif.2or2 PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS mmcif SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( mmcif.8g7u /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=mmcif.8g7u]==])
set_tests_properties( mmcif.8g7u PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS mmcif SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( mmcif.tokenizer /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=mmcif.tokenizer]==])
set_tests_properties( mmcif.tokenizer PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS mmcif SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( mmcif.parse_section /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=mmcif.parse_section]==])
set_tests_properties( mmcif.parse_section PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS mmcif SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( mmcif.parse_2or2_comprehensive /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=mmcif.parse_2or2_comprehensive]==])
set_tests_properties( mmcif.parse_2or2_comprehensive PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS mmcif SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( mmcif.nonexistent_file /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=mmcif.nonexistent_file]==])
set_tests_properties( mmcif.nonexistent_file PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS mmcif SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( mmcif.advance_to_next_control /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=mmcif.advance_to_next_control]==])
set_tests_properties( mmcif.advance_to_next_control PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS mmcif SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.hbonds /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.hbonds]==])
set_tests_properties( util.hbonds PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.bonds /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.bonds]==])
set_tests_properties( util.bonds PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.inst /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.inst]==])
set_tests_properties( util.inst PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.backbone /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.backbone]==])
set_tests_properties( util.backbone PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.structure /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.structure]==])
set_tests_properties( util.structure PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.rmsd /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.rmsd]==])
set_tests_properties( util.rmsd PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.com /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.com]==])
set_tests_properties( util.com PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.structures /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.structures]==])
set_tests_properties( util.structures PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.rings_common /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.rings_common]==])
set_tests_properties( util.rings_common PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.rings_c60 /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.rings_c60]==])
set_tests_properties( util.rings_c60 PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.rings_c720 /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.rings_c720]==])
set_tests_properties( util.rings_c720 PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.rings_14kr /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.rings_14kr]==])
set_tests_properties( util.rings_14kr PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.rings_trytophan_pdb /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.rings_trytophan_pdb]==])
set_tests_properties( util.rings_trytophan_pdb PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.rings_trytophan_xyz /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.rings_trytophan_xyz]==])
set_tests_properties( util.rings_trytophan_xyz PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.rings_full /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.rings_full]==])
set_tests_properties( util.rings_full PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.rings_ciprofloxacin /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.rings_ciprofloxacin]==])
set_tests_properties( util.rings_ciprofloxacin PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.structure_matching_amyloid_chain /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.structure_matching_amyloid_chain]==])
set_tests_properties( util.structure_matching_amyloid_chain PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.structure_matching_PFTAA /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.structure_matching_PFTAA]==])
set_tests_properties( util.structure_matching_PFTAA PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.structure_matching_PFTAA_ring /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.structure_matching_PFTAA_ring]==])
set_tests_properties( util.structure_matching_PFTAA_ring PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.structure_matching_smiles /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.structure_matching_smiles]==])
set_tests_properties( util.structure_matching_smiles PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.parse_smiles /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.parse_smiles]==])
set_tests_properties( util.parse_smiles PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.radix_sort /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.radix_sort]==])
set_tests_properties( util.radix_sort PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( util.entity_instance /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=util.entity_instance]==])
set_tests_properties( util.entity_instance PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( unit.print /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=unit.print]==])
set_tests_properties( unit.print PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS unit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( unit.from_string /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=unit.from_string]==])
set_tests_properties( unit.from_string PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS unit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( unit.convert /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=unit.convert]==])
set_tests_properties( unit.convert PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS unit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.common_subexpression_elimination /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.common_subexpression_elimination]==])
set_tests_properties( script.common_subexpression_elimination PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.type_equal /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.type_equal]==])
set_tests_properties( script.type_equal PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.basic_expressions /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.basic_expressions]==])
set_tests_properties( script.basic_expressions PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.type_compatability /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.type_compatability]==])
set_tests_properties( script.type_compatability PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.assignment /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.assignment]==])
set_tests_properties( script.assignment PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.array /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.array]==])
set_tests_properties( script.array PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.array_subscript /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.array_subscript]==])
set_tests_properties( script.array_subscript PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.dim_op /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.dim_op]==])
set_tests_properties( script.dim_op PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.selection /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.selection]==])
set_tests_properties( script.selection PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.stride_procedures_selectors /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.stride_procedures_selectors]==])
set_tests_properties( script.stride_procedures_selectors PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.compile_script /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.compile_script]==])
set_tests_properties( script.compile_script PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.implicit_conversion /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.implicit_conversion]==])
set_tests_properties( script.implicit_conversion PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.semantic /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.semantic]==])
set_tests_properties( script.semantic PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.selection_big /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.selection_big]==])
set_tests_properties( script.selection_big PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.dynamic_length /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.dynamic_length]==])
set_tests_properties( script.dynamic_length PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.property_compute /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.property_compute]==])
set_tests_properties( script.property_compute PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.stride_invalid_ranges /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.stride_invalid_ranges]==])
set_tests_properties( script.stride_invalid_ranges PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.parallel_evaluation /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.parallel_evaluation]==])
set_tests_properties( script.parallel_evaluation PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.parse_unary_binary /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.parse_unary_binary]==])
set_tests_properties( script.parse_unary_binary PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( script.visualize /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=script.visualize]==])
set_tests_properties( script.visualize PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS script SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( filter.centered /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=filter.centered]==])
set_tests_properties( filter.centered PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS filter SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( frame_cache.parallel_workload /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=frame_cache.parallel_workload]==])
set_tests_properties( frame_cache.parallel_workload PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS frame_cache SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( spatial_hash.small_periodic /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=spatial_hash.small_periodic]==])
set_tests_properties( spatial_hash.small_periodic PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS spatial_hash SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( spatial_hash.big /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=spatial_hash.big]==])
set_tests_properties( spatial_hash.big PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS spatial_hash SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( spatial_hash.n2 /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=spatial_hash.n2]==])
set_tests_properties( spatial_hash.n2 PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS spatial_hash SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( spatial_hash.test_correctness_centered /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=spatial_hash.test_correctness_centered]==])
set_tests_properties( spatial_hash.test_correctness_centered PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS spatial_hash SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( spatial_hash.test_correctness_ala /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=spatial_hash.test_correctness_ala]==])
set_tests_properties( spatial_hash.test_correctness_ala PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS spatial_hash SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( spatial_hash.test_correctness_ala_vec3 /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=spatial_hash.test_correctness_ala_vec3]==])
set_tests_properties( spatial_hash.test_correctness_ala_vec3 PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS spatial_hash SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( spatial_hash.test_correctness_water /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=spatial_hash.test_correctness_water]==])
set_tests_properties( spatial_hash.test_correctness_water PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS spatial_hash SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( spatial_hash.test_correctness_periodic_centered /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=spatial_hash.test_correctness_periodic_centered]==])
set_tests_properties( spatial_hash.test_correctness_periodic_centered PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS spatial_hash SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( spatial_hash.test_correctness_periodic_water /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=spatial_hash.test_correctness_periodic_water]==])
set_tests_properties( spatial_hash.test_correctness_periodic_water PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS spatial_hash SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( string_builder.all /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=string_builder.all]==])
set_tests_properties( string_builder.all PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS string_builder SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( base64.encode_decode /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=base64.encode_decode]==])
set_tests_properties( base64.encode_decode PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS base64 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( base64.enc_with_new_line /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=base64.enc_with_new_line]==])
set_tests_properties( base64.enc_with_new_line PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS base64 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( base64.not_multiple_of_four /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=base64.not_multiple_of_four]==])
set_tests_properties( base64.not_multiple_of_four PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS base64 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( base64.invalid_character /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=base64.invalid_character]==])
set_tests_properties( base64.invalid_character PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS base64 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xtc.bitread /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xtc.bitread]==])
set_tests_properties( xtc.bitread PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xtc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xtc.decode_bits /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xtc.decode_bits]==])
set_tests_properties( xtc.decode_bits PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xtc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xtc.trajectory_i /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xtc.trajectory_i]==])
set_tests_properties( xtc.trajectory_i PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xtc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xtc.catalyst /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xtc.catalyst]==])
set_tests_properties( xtc.catalyst PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xtc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.xyz_standard /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.xyz_standard]==])
set_tests_properties( xyz.xyz_standard PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.c60 /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.c60]==])
set_tests_properties( xyz.c60 PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.xyz_xmol /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.xyz_xmol]==])
set_tests_properties( xyz.xyz_xmol PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.xyz_tinker /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.xyz_tinker]==])
set_tests_properties( xyz.xyz_tinker PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.xyz_tinker_arc /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.xyz_tinker_arc]==])
set_tests_properties( xyz.xyz_tinker_arc PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.o2_arc /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.o2_arc]==])
set_tests_properties( xyz.o2_arc PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.h2o_arc /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.h2o_arc]==])
set_tests_properties( xyz.h2o_arc PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.ch4_arc /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.ch4_arc]==])
set_tests_properties( xyz.ch4_arc PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.extended_xyz /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.extended_xyz]==])
set_tests_properties( xyz.extended_xyz PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.extended1_xyz /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.extended1_xyz]==])
set_tests_properties( xyz.extended1_xyz PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.extended2_xyz /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.extended2_xyz]==])
set_tests_properties( xyz.extended2_xyz PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.extended_xyz_lattice_braced /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.extended_xyz_lattice_braced]==])
set_tests_properties( xyz.extended_xyz_lattice_braced PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.extended_xyz_lattice_array /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.extended_xyz_lattice_array]==])
set_tests_properties( xyz.extended_xyz_lattice_array PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.create_molecule /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.create_molecule]==])
set_tests_properties( xyz.create_molecule PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.trajectory_i /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.trajectory_i]==])
set_tests_properties( xyz.trajectory_i PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.comprehensive_c720 /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.comprehensive_c720]==])
set_tests_properties( xyz.comprehensive_c720 PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xyz.error_handling /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xyz.error_handling]==])
set_tests_properties( xyz.error_handling PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xyz SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xvg.rdf /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xvg.rdf]==])
set_tests_properties( xvg.rdf PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xvg SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xvg.energy /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xvg.energy]==])
set_tests_properties( xvg.energy PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xvg SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( xvg.lj_sr_lig_protein /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=xvg.lj_sr_lig_protein]==])
set_tests_properties( xvg.lj_sr_lig_protein PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS xvg SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( lammps.water_ethane_cubic /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=lammps.water_ethane_cubic]==])
set_tests_properties( lammps.water_ethane_cubic PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS lammps SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( lammps.water_ethane_triclinic /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=lammps.water_ethane_triclinic]==])
set_tests_properties( lammps.water_ethane_triclinic PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS lammps SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( lammps.read_standardASCII_lammpstrj_cubic /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=lammps.read_standardASCII_lammpstrj_cubic]==])
set_tests_properties( lammps.read_standardASCII_lammpstrj_cubic PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS lammps SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( lammps.read_standardASCII_lammpstrj_triclinic /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=lammps.read_standardASCII_lammpstrj_triclinic]==])
set_tests_properties( lammps.read_standardASCII_lammpstrj_triclinic PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS lammps SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( lammps.comprehensive_data_validation /home/runner/work/viamd/viamd/_codeql_build_dir/bin/md_unittest [==[--filter=lammps.comprehensive_data_validation]==])
set_tests_properties( lammps.comprehensive_data_validation PROPERTIES WORKING_DIRECTORY /home/runner/work/viamd/viamd/_codeql_build_dir/ext/mdlib/unittest LABELS lammps SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
set( allocator.default allocator.default_temp allocator.arena allocator.linear_generic allocator.ring_generic allocator.arena_extended allocator.vm_arena allocator.vm_arena_generic allocator.vm allocator.linear allocator.ring allocator.temp array.test atomic.enum_constants atomic.symbol_lookup atomic.symbol_from_number atomic.element_properties atomic.inference_water atomic.inference_amino_acid atomic.inference_nucleic_acid atomic.inference_ions atomic.inference_fallbacks atomic.backward_compatibility bitop.test bitfield.bit_op bitfield.realloc bitfield.general bitfield.serialization bitfield.deserialize_base64 bitfield.iterator element_guess_compat.all_pdb_validation str.parse_int str.perf_int str.parse_float str.perf_float str.extract_line str.edit_distance str.count_equal_chars hash.u32 hash.u64 hash.custom_type edr.pullout edr.orires edr.ener edr.dhdl edr.comprehensive_validation edr.nonexistent_file cube.read_benzene cube.read_A2B2 cube.serialize_deserialize cube.nonexistent_file cube.empty_path intrinsics.memset intrinsics.memcpy intrinsics.test simd.sin_cos simd.hsum simd.hmax simd.hmin simd.exp simd.fast_pow vec_math.mat3 vec_math.mat4 os.path_canonical os.path_relative os.ram os.mem os.thread os.mutex os.semaphore os.file_read_lines pdb.parse_ordinary pdb.tryptophan pdb.unmatched_model_entry pdb.parse_trajectory pdb.trajectory_i pdb.create_system pdb.parse_nonexistent_file pdb.parse_empty_path gro.parse_small gro.parse_big gro.parse_small_water gro.nonexistent_file trr.trajectory_i trr.nonexistent_file trr.frame_boundary_conditions mmcif.1fez mmcif.2or2 mmcif.8g7u mmcif.tokenizer mmcif.parse_section mmcif.parse_2or2_comprehensive mmcif.nonexistent_file mmcif.advance_to_next_control util.hbonds util.bonds util.inst util.backbone util.structure util.rmsd util.com util.structures util.rings_common util.rings_c60 util.rings_c720 util.rings_14kr util.rings_trytophan_pdb util.rings_trytophan_xyz util.rings_full util.rings_ciprofloxacin util.structure_matching_amyloid_chain util.structure_matching_PFTAA util.structure_matching_PFTAA_ring util.structure_matching_smiles util.parse_smiles util.radix_sort util.entity_instance unit.print unit.from_string unit.convert script.common_subexpression_elimination script.type_equal script.basic_expressions script.type_compatability script.assignment script.array script.array_subscript script.dim_op script.selection script.stride_procedures_selectors script.compile_script script.implicit_conversion script.semantic script.selection_big script.dynamic_length script.property_compute script.stride_invalid_ranges script.parallel_evaluation script.parse_unary_binary script.visualize filter.centered frame_cache.parallel_workload spatial_hash.small_periodic spatial_hash.big spatial_hash.n2 spatial_hash.test_correctness_centered spatial_hash.test_correctness_ala spatial_hash.test_correctness_ala_vec3 spatial_hash.test_correctness_water spatial_hash.test_correctness_periodic_centered spatial_hash.test_correctness_periodic_water string_builder.all base64.encode_decode base64.enc_with_new_line base64.not_multiple_of_four base64.invalid_character xtc.bitread xtc.decode_bits xtc.trajectory_i xtc.catalyst xyz.xyz_standard xyz.c60 xyz.xyz_xmol xyz.xyz_tinker xyz.xyz_tinker_arc xyz.o2_arc xyz.h2o_arc xyz.ch4_arc xyz.extended_xyz xyz.extended1_xyz xyz.extended2_xyz xyz.extended_xyz_lattice_braced xyz.extended_xyz_lattice_array xyz.create_molecule xyz.trajectory_i xyz.comprehensive_c720 xyz.error_handling xvg.rdf xvg.energy xvg.lj_sr_lig_protein lammps.water_ethane_cubic lammps.water_ethane_triclinic lammps.read_standardASCII_lammpstrj_cubic lammps.read_standardASCII_lammpstrj_triclinic lammps.comprehensive_data_validation)
