#pragma once

#include <core/md_vec_math.h>
#include <core/md_str.h>

#if MD_ENABLE_GPU
#include <core/md_gpu.h>
#endif

namespace volume {

void initialize();
void shutdown();

mat4_t compute_model_to_world_matrix(vec3_t min_world_aabb, vec3_t max_world_aabb);
mat4_t compute_world_to_model_matrix(vec3_t min_world_aabb, vec3_t max_world_aabb);
mat4_t compute_texture_to_model_matrix(int dim_x, int dim_y, int dim_z);
mat4_t compute_model_to_texture_matrix(int dim_x, int dim_y, int dim_z);

// Simple transfer function 
void compute_transfer_function_texture_simple(uint32_t* texture, int implot_colormap, float alpha_scale = 1.0f, int resolution = 128);

enum ramp_type_t {
    RAMP_TYPE_SAWTOOTH,         /* Alpha ramp: /|/|/|/|   */
    RAMP_TYPE_TRIANGLE,         /* Alpha ramp: /\/\/\/\   */
};

// Create a transfer function texture with an alpha ramp generated by an underlying function
// If you want a monotonic ramp (standard), you can for example use SAWTOOTH with a period of 1
void compute_transfer_function_texture(uint32_t* texture, int implot_colormap, ramp_type_t ramp_type = RAMP_TYPE_SAWTOOTH, float ramp_scale = 1.0f, float ramp_period = 1.0001f, int resolution = 128);

// Precomputes a 3D texture of interpolated point colors from a list of colored points (e.g. for splatting or point-based rendering)
// It uses Shepard interpolation combined with RDFs encoded as gaussians to interpolate the colors of the points onto a regular grid.
void compute_point_color_volume(uint32_t vol_texture, const int volume_dim[3], const float voxel_spacing[3], const float world_to_model[4][4], const float index_to_world[4][4], const vec4_t* point_xyzw, const uint32_t* point_color, size_t point_count, double power = 4.0f);

/*
    Renders a volumetric texture using OpenGL.
    - volume_texture: An OpenGL 3D texture containing the data
    - tf_texture:     An OpenGL 1D texture containing the transfer function
    - depth_texture:  An OpenGL 2D texture containing the depth data in the frame (for stopping ray traversal)
    - model_matrix:   Matrix containing model to world transformation of the volume, which is assumed to occupy a unit cube [0,1] in its model-space
    - view_matrix:    Matrix containing world to view transformation of the camera
    - proj_matrix:    Matrix containing view to clip transformation of the camera
    - density_scale:  global scaling of density
    - alpha_scale:    global alpha scaling of the transfer function
    - isosurface:     information on isovalues and associated colors
    - voxel_spacing:  spacing of voxels in world space
    - clip_planes:    define a subvolume (min, max)[0-1] which represents the visible portion of the volume
*/

struct RenderDesc {
    struct {
        uint32_t depth = 0;
        uint32_t color = 0;
        uint32_t width = 0;
        uint32_t height = 0;
        bool clear_color = false;
    } render_target;

    struct {
        uint32_t density_volume = 0;
        uint32_t color_volume   = 0;
        uint32_t transfer_function = 0;
    } texture;

    struct {
        mat4_t model = {};
        mat4_t view = {};
        mat4_t proj = {};
        mat4_t inv_proj = {};
    } matrix;

    struct {
        vec3_t min = {0, 0, 0};
        vec3_t max = {1, 1, 1};
    } clip_volume;

    struct {
        // Enables temporal jittering of the ray-casting offset
        bool enabled = false;
    } temporal;

    struct {
        bool enabled = false;
        size_t count = 0;
        const float* values = NULL;
        const vec4_t* colors = NULL;
        const float* optical_densities = NULL; // Optional per-iso surface optical density (τ) to modulate the absorption when inside the surface (if not provided, a value of 0 is used per iso surface)
        bool use_color_volume = false;  // If true, the color of the iso surfaces will determined by the color volume instead of the provided iso.colors
    } iso;

    struct {
        bool enabled = false;
        float min_tf_value = 0.0f;
        float max_tf_value = 1.0f;
    } dvr;

    // A simplified shading model based on Cook-Torrance
    // Static enviromental radiance (uniformly lit from all directions)
    // 1 directional light positioned at {1,1,1} in viewspace

    // env_radiance: The uniformly incomming radiance from all directions
    // dir_radiance: The directional radiance incomming from a directional light
    // roughness: Approximates the micro-roughness of the surface
    // A value of 0.0 would approximate a perfectly smooth surface
    // A value of 1.0 would approximate a perfectly 'diffuse' surface

    // ior: corresponds to the Index of refraction of the iso surfaces.
    // A value of 1.5 is recommended and roughly approximates plastic

    struct {
        vec3_t env_radiance = {0,0,0};
        float roughness = 0.4f;
        vec3_t dir_radiance = {1,1,1};
        float ior = 1.5f;
        float exposure = 1.0f;
        float gamma = 2.2f;
    } shading;

    vec3_t voxel_spacing = {};
};

void render_volume(const RenderDesc& desc);

#if MD_ENABLE_GPU

static constexpr uint32_t GPU_ISO_MAX_SURFACE_COUNT = 8;
static constexpr uint32_t GPU_ISO_PARAM_BUFFER_COUNT = 3;

enum GpuIsoRenderFlags : uint32_t {
    GPU_ISO_RENDER_FLAG_NONE = 0,
    GPU_ISO_RENDER_FLAG_USE_ABS_FIELD = 1u << 0,
    GPU_ISO_RENDER_FLAG_TEMPORAL_JITTER = 1u << 1,
};

struct GpuIsoRenderer {
    md_gpu_device_t device = nullptr;
    md_gpu_compute_pipeline_t pipeline = nullptr;
    md_gpu_sampler_t linear_sampler = nullptr;
    md_gpu_buffer_t param_buffers[GPU_ISO_PARAM_BUFFER_COUNT] = {};
    uint32_t param_buffer_idx = 0;
};

struct GpuIsoRenderDesc {
    struct {
        md_gpu_image_t color = nullptr;
        uint32_t width = 0;
        uint32_t height = 0;
    } target;

    struct {
        md_gpu_image_t scalar_volume = nullptr;
        uint32_t dim[3] = {};
        mat4_t texture_to_world = {
            1, 0, 0, 0,
            0, 1, 0, 0,
            0, 0, 1, 0,
            0, 0, 0, 1,
        };
        vec3_t clip_min = {0, 0, 0};
        vec3_t clip_max = {1, 1, 1};
    } volume;

    struct {
        mat4_t view = {
            1, 0, 0, 0,
            0, 1, 0, 0,
            0, 0, 1, 0,
            0, 0, 0, 1,
        };
        mat4_t proj = {
            1, 0, 0, 0,
            0, 1, 0, 0,
            0, 0, 1, 0,
            0, 0, 0, 1,
        };
    } matrix;

    struct {
        size_t count = 0;
        const float* values = nullptr;
        const vec4_t* colors = nullptr;
    } iso;

    struct {
        vec3_t env_radiance = {0, 0, 0};
        float roughness = 0.4f;
        vec3_t dir_radiance = {1, 1, 1};
        float specular = 0.04f;
        vec3_t light_dir_world = {1, 1, 1};
        float exposure = 1.0f;
        float gamma = 2.2f;
        float interior_extinction = 0.0f;
    } shading;

    struct {
        float sampling_rate = 2.0f;
    } sampling;

    uint32_t flags = GPU_ISO_RENDER_FLAG_NONE;
};

bool gpu_iso_renderer_init(GpuIsoRenderer* renderer, md_gpu_device_t device);
void gpu_iso_renderer_free(GpuIsoRenderer* renderer);
bool render_volume_iso_gpu(md_gpu_command_buffer_t cmd, GpuIsoRenderer* renderer, const GpuIsoRenderDesc& desc);

#endif


}  // namespace volume
