#pragma once

#include <core/md_vec_math.h>
#include <core/md_str.h>

namespace volume {

void initialize();
void shutdown();

// GPU time spent in the volume passes, averaged per frame over the last few frames. Measured with
// GL_TIME_ELAPSED queries that are read back a few frames late, so collecting them never stalls.
enum TimingStage {
    TimingStage_BlockMinMax,
    TimingStage_EntryExit,
    TimingStage_Raycast,
    TimingStage_Count
};

struct GpuTimings {
    float ms[TimingStage_Count] = {};
    float total_ms = 0.0f;
};

// Call once per frame: collects finished queries and publishes the averages
void timings_new_frame();
GpuTimings timings_get();
const char* timing_stage_name(TimingStage stage);

// The isosurface renderer keeps a coarse min/max grid per density volume to skip empty space, and has to
// be told when a volume's texels change: call this after every upload into (or evaluation onto) a density
// volume texture, and after (re)allocating one. A volume that is never announced still works, but its
// grid is built once and then not again.
void notify_data_changed(uint32_t volume_texture);

// Changes every time notify_data_changed() is called for the texture, and never repeats for it; 0 for a
// texture never announced. For callers that cache what they render from a volume.
uint64_t data_version(uint32_t volume_texture);

mat4_t compute_model_to_world_matrix(vec3_t min_world_aabb, vec3_t max_world_aabb);
mat4_t compute_world_to_model_matrix(vec3_t min_world_aabb, vec3_t max_world_aabb);
mat4_t compute_texture_to_model_matrix(int dim_x, int dim_y, int dim_z);
mat4_t compute_model_to_texture_matrix(int dim_x, int dim_y, int dim_z);

// Simple transfer function 
void compute_transfer_function_texture_simple(uint32_t* texture, int implot_colormap, float alpha_scale = 1.0f, int resolution = 128);

enum ramp_type_t {
    RAMP_TYPE_SAWTOOTH,         /* Alpha ramp: /|/|/|/|   */
    RAMP_TYPE_TRIANGLE,         /* Alpha ramp: /\/\/\/\   */
};

// Create a transfer function texture with an alpha ramp generated by an underlying function
// If you want a monotonic ramp (standard), you can for example use SAWTOOTH with a period of 1
void compute_transfer_function_texture(uint32_t* texture, int implot_colormap, ramp_type_t ramp_type = RAMP_TYPE_SAWTOOTH, float ramp_scale = 1.0f, float ramp_period = 1.0001f, int resolution = 128);

// Precomputes a 3D texture of interpolated point colors from a list of colored points (e.g. for splatting or point-based rendering)
// It uses Shepard interpolation combined with RDFs encoded as gaussians to interpolate the colors of the points onto a regular grid.
void compute_point_color_volume(uint32_t vol_texture, const int volume_dim[3], const float voxel_spacing[3], const float world_to_model[4][4], const float index_to_world[4][4], const vec4_t* point_xyzw, const uint32_t* point_color, size_t point_count, double power = 4.0f);

// The two renderers below share no state and are never combined in one pass: a view shows either
// the isosurfaces of a volume or a direct volume rendering of it.
//
// Common to both:
//  - render_target.depth: the depth of the opaque scene (optional), rays stop there
//  - render_target.color: the texture to blend into (0 = the currently bound framebuffer)
//  - matrix.model: places the volume, which occupies the unit cube [0,1] of its model (= texture) space
//  - clip_volume: the visible sub-box of the volume, in its model space

// ISOSURFACES
// Up to 8 isovalues, each a surface with its own colour and an optional optical density (tau): the
// absorption accumulated while the ray is inside that surface. The surfaces are those of the trilinearly
// interpolated field. A point is inside the surface of value v when the density d >= v (v >= 0) or d <= v
// (v < 0). Two ways to find them along a ray (iso.exact):
//  - fast: one filtered sample per voxel, crossings refined between samples. A part of a surface thinner
//    than about a voxel along the ray can be missed, and up close or at grazing angles the sampling can
//    show. A finer volume makes both smaller.
//  - exact: every cell the ray passes through is intersected exactly, so no part of a surface is missed
//    and where a crossing lies does not depend on any sampling. Roughly twice the cost of fast.
//
// The output is linear, premultiplied radiance with coverage in alpha, blended over the target with
// (ONE, ONE_MINUS_SRC_ALPHA). It is meant for an HDR target (RGBA16F) that is composited over the
// scene before tone mapping (postprocess_pipeline::Inputs::transparency_hdr), and it is lit with the
// same model as the deferred compose pass so that it matches the opaque geometry.
struct IsoRenderDesc {
    struct {
        uint32_t depth = 0;
        uint32_t color = 0;
        uint32_t width = 0;
        uint32_t height = 0;
        bool clear_color = false;
    } render_target;

    struct {
        uint32_t density_volume = 0;
        uint32_t color_volume   = 0;    // optional, see iso.use_color_volume
        uint32_t field_volume   = 0;    // same grid as density_volume, see iso.use_field
        uint32_t field_colormap = 0;    // 2D, N x 1
    } texture;

    struct {
        mat4_t model = {};
        mat4_t view = {};
        mat4_t proj = {};
        mat4_t inv_proj = {};
    } matrix;

    struct {
        vec3_t min = {0, 0, 0};
        vec3_t max = {1, 1, 1};
    } clip_volume;

    struct {
        size_t count = 0;
        const float* values = NULL;
        const vec4_t* colors = NULL;
        const float* optical_densities = NULL;  // optional, 0 per surface when not given
        bool use_color_volume = false;          // the surfaces take their colour from the colour volume instead of iso.colors
        bool use_field = false;                 // the surfaces are coloured by the field volume through the field colormap, over field.range_*
        bool exact = false;                     // exact intersection instead of one sample per voxel, see above
    } iso;

    // The range of the field the colour map spans, when iso.use_field
    struct {
        float range_beg = 0.0f;
        float range_end = 1.0f;
    } field;

    // A simplified Cook-Torrance model: uniform environment radiance and one directional light at
    // {1,1,1} in view space, as in the deferred compose pass. roughness in [0,1], ior of the surfaces
    // (1.5 ~ plastic, which is the F0 = 0.04 the compose pass uses).
    struct {
        vec3_t env_radiance = {0,0,0};
        float roughness = 0.4f;
        vec3_t dir_radiance = {1,1,1};
        float ior = 1.5f;
    } shading;
};

// Returns true when the colour target holds this pass's result (cleared and/or drawn into), false when
// nothing was done (no valid volume or program), in which case a requested clear did not happen either.
bool render_isosurfaces(const IsoRenderDesc& desc);

// DIRECT VOLUME RENDERING
// Emission-absorption through a 1D transfer function (a colour map with an alpha ramp), applied to
// the density mapped from [tf.min_value, tf.max_value] to [0,1]. The colours are the colour map's
// own, blended in display space.
struct DvrRenderDesc {
    struct {
        uint32_t depth = 0;
        uint32_t color = 0;
        uint32_t width = 0;
        uint32_t height = 0;
        bool clear_color = false;
    } render_target;

    struct {
        uint32_t density_volume = 0;
        uint32_t transfer_function = 0;    // 2D, N x 1
    } texture;

    struct {
        mat4_t model = {};
        mat4_t view = {};
        mat4_t proj = {};
        mat4_t inv_proj = {};
    } matrix;

    struct {
        vec3_t min = {0, 0, 0};
        vec3_t max = {1, 1, 1};
    } clip_volume;

    struct {
        bool enabled = false;
    } temporal;

    struct {
        float min_value = 0.0f;
        float max_value = 1.0f;
    } tf;
};

// Premultiplied colour + coverage, blended over the target with (ONE, ONE_MINUS_SRC_ALPHA)
void render_dvr(const DvrRenderDesc& desc);


}  // namespace volume
