name: MacOS (Clang)

on: [push]

jobs:
    ci:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v2
        - name: prepare
          run: |
            git submodule update --init --recursive
        - name: install dependencies
          run: |
            brew install hdf5
        - name: cmake
          run: |
            cmake . -DHDF5_ROOT=$(brew --prefix hdf5)
        - name: build
          run: |
            make -j 4
