name: MacOS (Clang)

on: [push]

jobs:
    ci:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
        - name: install dependencies
          run: |
            brew install hdf5
        - name: cmake
          run: |
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DHDF5_ROOT=$(brew --prefix hdf5) -DVIAMD_ENABLE_TREXIO=OFF
        - name: build
          run: |
            cmake --build build -j 4
