name: Windows ARM64 (MSVC)

on: [push]

jobs:
    ci:
        runs-on: windows-11-arm
        steps:
        - uses: actions/checkout@v4
        - name: prepare
          run: |
            git submodule update --init --recursive
        - name: cmake
          run: |
            cmake .
        - name: build
          run: |
            cmake --build . --config Release -- /nologo /verbosity:minimal /maxcpucount:4
        - name: test
          run: |
            ctest -C Release -R '^viamd_test$' --output-on-failure --no-tests=error
